kernel: ifdef MODULE for __stack_chk_guard
It will cause duplicate symbols when built-in tracepoint hook

ld.lld: error: duplicate symbol: __stack_chk_guard
>>> defined in arch/arm64/built-in.a(kernel/process.o)
>>> defined in drivers/built-in.a(kernelsu/ksu.o)

I think we should make it lkm only for now

Reported-by: bachnxuan <bachnxuan@gmail.com>
Signed-off-by: AlexLiuDev233 <wzylin11@outlook.com>